IF(PIRANHA_INCLUDE_DIR)
	# Already in cache, be silent
	SET(PIRANHA_FIND_QUIETLY TRUE)
ENDIF(PIRANHA_INCLUDE_DIR)

FIND_PATH(PIRANHA_INCLUDE_DIR NAMES piranha/piranha.hpp)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(GMP DEFAULT_MSG GMP_INCLUDE_DIR GMP_LIBRARIES)

MARK_AS_ADVANCED(PIRANHA_INCLUDE_DIR)
