name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Ubuntu workflow
  ubuntu-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: bash tools/gha_ubuntu_asan.sh
  # macOS workflow
  osx-debug:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: bash tools/gha_osx_debug.sh
  # Windows workflow
  windows-release:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v5
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: audi_devel
          environment-file: audi_devel.yml
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          auto-activate-base: false
      - name: Build
        run: .\tools\gha_windows_release.ps1
        shell: pwsh
  ubuntu_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: bash tools/gha_ubuntu_coverage.sh
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
